### ISSUE TITLE
Missing 'uuid4' module

### ISSUE THREAD

**Issue by kiptoomm** [roam-ai/roam-js#3]
I upgraded to v0.0.3 of this library and get the following error, even after reinstalling my dependencies afresh:

```
0.chunk.js:589324 Uncaught Error: Cannot find module 'uuid4'
    at webpackMissingModule (0.chunk.js:589324)
    at Object../node_modules/roam-js/src/index.js (0.chunk.js:589324)
    at __webpack_require__ (bundle.js:785)
    at fn (bundle.js:151)
    at Module../src/components/map/Map.js (main.chunk.js:9315)
    at __webpack_require__ (bundle.js:785)
    at fn (bundle.js:151)
    at Module../src/pages/admin/index.js (main.chunk.js:20420)
    at __webpack_require__ (bundle.js:785)
    at fn (bundle.js:151)
    at Module../src/routes/App.js (main.chunk.js:31626)
    at __webpack_require__ (bundle.js:785)
    at fn (bundle.js:151)
    at Module../src/index.js (main.chunk.js:10727)
    at __webpack_require__ (bundle.js:785)
    at fn (bundle.js:151)
    at Object.1 (main.chunk.js:32226)
    at __webpack_require__ (bundle.js:785)
    at checkDeferredModules (bundle.js:46)
    at Array.webpackJsonpCallback [as push] (bundle.js:33)
    at main.chunk.js:1
webpackMissingModule @ 0.chunk.js:589324
./node_modules/roam-js/src/index.js @ 0.chunk.js:589324
__webpack_require__ @ bundle.js:785
fn @ bundle.js:151
./src/components/map/Map.js @ main.chunk.js:9315
__webpack_require__ @ bundle.js:785
fn @ bundle.js:151
./src/pages/admin/index.js @ main.chunk.js:20420
__webpack_require__ @ bundle.js:785
fn @ bundle.js:151
./src/routes/App.js @ main.chunk.js:31626
__webpack_require__ @ bundle.js:785
fn @ bundle.js:151
./src/index.js @ main.chunk.js:10727
__webpack_require__ @ bundle.js:785
fn @ bundle.js:151
1 @ main.chunk.js:32226
__webpack_require__ @ bundle.js:785
checkDeferredModules @ bundle.js:46
webpackJsonpCallback @ bundle.js:33
(anonymous) @ main.chunk.js:1
fs.js:3 ./node_modules/roam-js/src/index.js
Module not found: Can't resolve 'uuid4' in '~/my-project/node_modules/roam-js/src'
```

My stack:
* macOS Catalina
* React ^16.13.1
* yarn for package management

**Comment by NaveenROAM** [comment]
add roam-js as an unpkg script in your html file like this:`<script
      crossorigin
      src="https://unpkg.com/roam-js@0.0.3/dist/roam.min.js"
    ></script>` inside body tag
and wherever you are using roam-js just do `window.roam` instead of roam

**Comment by srinath-geospark** [comment]
Hi @kiptoomm . 
Thanks for bringing this to our notice. 
We have released a new version of roam-js version: 0.0.4 in whcih we have changed the dependency of uuid4 to uuid. 
Request you to try the latest version and close this issue if it works.

**Comment by kiptoomm** [comment]
@srinath-geospark @NaveenROAM I have upgraded to v0.0.4, thanks for fixing it quickly. I have also added roam-js as an unpkg script as advised. 

However, I'm seeing a 500 error with this subscribe code:

```
const userId = '<some roam user id>';
window.roam.Initialize(roamPublishKey)
        .then((roamClient) => {
            roamClient.userSubscription(roamUserId)
            .then((subscription)=>{
                subscription.subscribe()
                .then((msg)=>{
                    console.log(`user ${userId}, roam subscription: ${msg}`);
                })
            })
            .catch((err)=>{
                throw(err)
            });

            roamClient.setCallback(async function(message) {
                console.log(`user ${userId} roam location result received: `, message)
            })
        })
        .catch((error) => {
            console.log("error with subscribe location: ", error)
        });
```

The error:
```
Error while API call: Error: Request failed with status code 500
```

Any idea?

**Comment by kiptoomm** [comment]
> @srinath-geospark @NaveenROAM I have upgraded to v0.0.4, thanks for fixing it quickly. I have also added roam-js as an unpkg script as advised.
> 
> However, I'm seeing a 500 error with this subscribe code:
> 
> ```
> const userId = '<some roam user id>';
> window.roam.Initialize(roamPublishKey)
>         .then((roamClient) => {
>             roamClient.userSubscription(roamUserId)
>             .then((subscription)=>{
>                 subscription.subscribe()
>                 .then((msg)=>{
>                     console.log(`user ${userId}, roam subscription: ${msg}`);
>                 })
>             })
>             .catch((err)=>{
>                 throw(err)
>             });
> 
>             roamClient.setCallback(async function(message) {
>                 console.log(`user ${userId} roam location result received: `, message)
>             })
>         })
>         .catch((error) => {
>             console.log("error with subscribe location: ", error)
>         });
> ```
> 
> The error:
> 
> ```
> Error while API call: Error: Request failed with status code 500
> ```
> 
> Any idea?

![Screen Shot 2021-07-13 at 2 43 35 PM](https://user-images.githubusercontent.com/1447912/125446111-9adc288f-1006-40ca-967a-19597d09b68c.png)

**Comment by srinath-geospark** [comment]
@kiptoomm we checked the logs and we find that you are passing in invalid publishable key to initialize roam-js ("undefined").
We have updated the status code and message for the API from the backend.
Request you to kindly use the publishable key which you can find in our [dashboard](https://roam.ai/dashboard) to initialize the roam-js.

**Comment by kiptoomm** [comment]
@srinath-geospark you're right. I've set the publishable key to a valid value and the issue is gone. 👍
