### ISSUE TITLE
> @srinath-geospark @NaveenROAM I have upgraded to v0.0.4, thanks for fixing it quickly. I have also added roam-js as an unpkg script as advised.

### ISSUE THREAD

**Issue by jothipriyadharshanr** [roam-ai/roam-js#5]
> @srinath-geospark @NaveenROAM I have upgraded to v0.0.4, thanks for fixing it quickly. I have also added roam-js as an unpkg script as advised.
> 
> However, I'm seeing a 500 error with this subscribe code:
> 
> ```
> const userId = '<some roam user id>';
> window.roam.Initialize(roamPublishKey)
>         .then((roamClient) => {
>             roamClient.userSubscription(roamUserId)
>             .then((subscription)=>{
>                 subscription.subscribe()
>                 .then((msg)=>{
>                     console.log(`user ${userId}, roam subscription: ${msg}`);
>                 })
>             })
>             .catch((err)=>{
>                 throw(err)
>             });
> 
>             roamClient.setCallback(async function(message) {
>                 console.log(`user ${userId} roam location result received: `, message)
>             })
>         })
>         .catch((error) => {
>             console.log("error with subscribe location: ", error)
>         });
> ```
> 
> The error:
> 
> ```
> Error while API call: Error: Request failed with status code 500
> ```
> 
> Any idea?

![Screen Shot 2021-07-13 at 2 43 35 PM](https://user-images.githubusercontent.com/1447912/125446111-9adc288f-1006-40ca-967a-19597d09b68c.png)

_Originally posted by @kiptoomm in https://github.com/roam-ai/roam-js/issues/3#issuecomment-879017564_

**Comment by jothipriyadharshanr** [comment]
> > @srinath-geospark @NaveenROAM I have upgraded to v0.0.4, thanks for fixing it quickly. I have also added roam-js as an unpkg script as advised.
> > However, I'm seeing a 500 error with this subscribe code:
> > ```
> > const userId = '<some roam user id>';
> > window.roam.Initialize(roamPublishKey)
> >         .then((roamClient) => {
> >             roamClient.userSubscription(roamUserId)
> >             .then((subscription)=>{
> >                 subscription.subscribe()
> >                 .then((msg)=>{
> >                     console.log(`user ${userId}, roam subscription: ${msg}`);
> >                 })
> >             })
> >             .catch((err)=>{
> >                 throw(err)
> >             });
> > 
> >             roamClient.setCallback(async function(message) {
> >                 console.log(`user ${userId} roam location result received: `, message)
> >             })
> >         })
> >         .catch((error) => {
> >             console.log("error with subscribe location: ", error)
> >         });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The error:
> > ```
> > Error while API call: Error: Request failed with status code 500
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any idea?
> 
> ![Screen Shot 2021-07-13 at 2 43 35 PM](https://user-images.githubusercontent.com/1447912/125446111-9adc288f-1006-40ca-967a-19597d09b68c.png)
> 
> _Originally posted by @kiptoomm in [#3 (comment)](https://github.com/roam-ai/roam-js/issues/3#issuecomment-879017564)_

@kiptoomm we checked the logs and we find that you are passing in invalid publishable key to initialize roam-js ("undefined").
We have updated the status code and message for the API from the backend.
Request you to kindly use the publishable key which you can find in our dashboard to initialize the roam-js.

**Comment by srinath-geospark** [comment]
Closing issue as it was confirmed by @kiptoomm in #3  [comment](https://github.com/roam-ai/roam-js/issues/3#issuecomment-879395992)
